version: "3.7"
networks:
  monitor:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.34.0-rc.1
    container_name: prometheus
    hostname: prometheus
    networks:
      - monitor
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "/opt/docker/monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/opt/docker/monitor/prometheus/node_down.yml:/etc/prometheus/node_down.yml"
      - "/opt/docker/monitor/prometheus/data:/prometheus"
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    hostname: grafana
    networks:
      - monitor
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "/opt/docker/monitor/prometheus/grafana/data:/var/lib/grafana"

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor