version: '3.6'
services:
  web:
    container_name: gitlab
    image: gitlab/gitlab-ce:14.7.3-ce.0
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: external_url 'http://gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '23:22'
    volumes:
      - '/opt/docker/devops/gitlab/conf:/etc/gitlab'
      - '/opt/docker/devops/gitlab/logs:/var/log/gitlab'
      - '/opt/docker/devops/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

#    user = User.where(username:"root").first
#    user.password = "root"
#    user.password_confirmation ="root"
#    user.save!