version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 1001:80
      - 1443:443
    volumes:
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
    privileged: true