version: "3.9"

networks:
  rich:
    name: rich
    external: true

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
     # - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    networks:
      - rich
