version: "3.9"

networks:
  rich:
    name: rich
    driver: bridge

services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    env_file:
      - ${USER_DIR}/nacos/.env
    volumes:
      - ${USER_DIR}/nacos/log:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
    networks:
      - rich


  mysql:
    image: nacos/nacos-mysql:${MYSQL_VERSION}
    container_name: mysql
    env_file:
      - ${USER_DIR}/mysql/.env
    volumes:
      - ${USER_DIR}/mysql/data/mysql-files:/var/lib/mysql-files
      - ${USER_DIR}/mysql/data/mysql:/var/lib/mysql
      - ${USER_DIR}/mysql/conf/my.cnf:/etc/mysql/my.cnf:rw
      - ${USER_DIR}/mysql/nacos-mysql.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
    ports:
      - "3306:3306"
    networks:
      - rich

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    privileged: true
    command:
      - /bin/bash
      - -c
      - |
        echo 551 > /proc/sys/net/core/somaxconn
        echo 1 > /proc/sys/vm/overcommit_memory
        redis-server /etc/conf/redis.conf
    volumes:
      - ${USER_DIR}/redis/data:/data:rw
      - ${USER_DIR}/redis/conf/:/etc/conf/
      - ${USER_DIR}/redis/log/:/opt/redis/log/:rw
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    networks:
      - rich

