version: "3.9"

networks:
  rich:
    name: rich
    driver: bridge

services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    env_file:
      - ${USER_DIR}/nacos/.env
    volumes:
      - ${USER_DIR}/nacos/log:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
    networks:
      - rich


  mysql:
    image: nacos/nacos-mysql:${MYSQL_VERSION}
    container_name: mysql
    env_file:
      - ${USER_DIR}/mysql/.env
    volumes:
      - ${USER_DIR}/mysql/data:/var/lib/mysql
      - ${USER_DIR}/mysql/nacos-mysql.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
    ports:
      - "3306:3306"
    networks:
      - rich

