version: '2'
services:
  namesrv:
    image: apacherocketmq/rocketmq:4.5.0-alpine
    container_name: rmqnamesrv
    hostname: rmqnamesrv
    environment:
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    ports:
      - 9876:9876
    volumes:
      - /opt/docker/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  broker:
    image: apacherocketmq/rocketmq:4.5.0-alpine
    container_name: broker1
    hostname: broker1
    depends_on:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
        NAMESRV_ADDR: "rmqnamesrv:9876"
        JAVA_OPT_EXT: "-server -Xms256m -Xmx256m"
    volumes:
      - /opt/docker/rocketmq/broker1/logs:/home/rocketmq/logs
      - /opt/docker/rocketmq/broker1/store:/home/rocketmq/store
      - /opt/docker/rocketmq/broker1/conf/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.5.0/conf/broker.conf

  #Service for another broker -- broker1
  broker1:
    image: apacherocketmq/rocketmq:4.5.0-alpine
    container_name: broker2
    hostname: broker2
    depends_on:
      - namesrv
    ports:
      - 10929:10909
      - 10931:10911
      - 10932:10912
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m"
    volumes:
      - /opt/docker/rocketmq/broker2/logs:/home/rocketmq/logs
      - /opt/docker/rocketmq/broker2/store:/home/rocketmq/store
      - /opt/docker/rocketmq/broker2/conf/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.5.0/conf/broker.conf

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: rocketmq-dashboard
    hostname: rocketmq-dashboard
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876"