version: '3'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    hostname: postgres
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/lib/postgresql/data