version: '3'

networks:
  demo:
    driver: bridge

services:
  zoo1:
    image: zookeeper:3.8.0
    container_name: zoo1
    hostname: zoo1
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
    networks:
      - demo
  zoo2:
    image: zookeeper:3.8.0
    container_name: zoo2
    hostname: zoo2
    restart: always
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog
    networks:
      - demo
  zoo3:
    image: zookeeper:3.8.0
    container_name: zoo3
    hostname: zoo3
    restart: always
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog
    networks:
      - demo

  kafka1:
    image: bitnami/kafka:3.2.0
    container_name: kafka1
    hostname: kafka1
    restart: always
    networks:
      - demo
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.206.139:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      ALLOW_PLAINTEXT_LISTENER: true
    volumes:
      - ./kafka1:/bitnami/kafka
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"

  kafka2:
    image: bitnami/kafka:3.2.0
    container_name: kafka2
    hostname: kafka2
    restart: always
    networks:
      - demo
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.206.139:9093
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      ALLOW_PLAINTEXT_LISTENER: true

    volumes:
      - ./kafka2:/bitnami/kafka
    depends_on:
      - kafka1

  kafka3:
    image: bitnami/kafka:3.2.0
    container_name: kafka3
    hostname: kafka3
    restart: always
    networks:
      - demo
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.206.139:9094
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      ALLOW_PLAINTEXT_LISTENER: true

    volumes:
      - ./kafka3:/bitnami/kafka
    depends_on:
      - kafka2