global:
  scrape_interval:     15s # 设置间隔15s，默认1分钟.
  evaluation_interval: 15s # 每15秒评估一次规则， 默认1分钟.

#设置报警插件
alerting:
  alertmanagers:
    - static_configs:
        #- targets: ['192.168.2.170:9093']

# 加载规则一次，并根据全局规则定期对其进行评估'evaluation_interval'.
rule_files:
  - "node_down.yml"

# 监控配置:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.2.170:8080']

  - job_name: 'node-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: ['node-exporter:9100']